/* Benchmark B: production Flash routed-decode layout with real quant decode.
 * This is deliberately a single-dispatch roofline probe; it is not inference
 * and does not participate in the engine/coordinator. */
#include <vulkan/vulkan.h>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <vector>
#include <string>
#include <algorithm>

static constexpr uint32_t IN=4096, MID=2048, OUT=4096, TOTAL=256, TOP=6;
static constexpr uint32_t IQ2_ROW=1056, Q2_ROW=672;
static constexpr VkDeviceSize GATE_BYTES=uint64_t(MID)*IQ2_ROW;
static constexpr VkDeviceSize DOWN_BYTES=uint64_t(OUT)*Q2_ROW;
static constexpr VkDeviceSize GATE_TOP=uint64_t(TOP)*GATE_BYTES;
static constexpr VkDeviceSize DOWN_TOP=uint64_t(TOP)*DOWN_BYTES;
static constexpr VkDeviceSize Q8_IN=16*292;
static constexpr VkDeviceSize Q80_BYTES=uint64_t(32768)*32*34;
static constexpr VkDeviceSize Q80_X_BYTES=32*36;
static constexpr VkDeviceSize Q80_LOGICAL_Q8=uint64_t(32768)*IN;
static constexpr VkDeviceSize IQ2_LOGICAL_Q8=uint64_t(TOP)*2*MID*16*256 + uint64_t(TOP)*16*256;
static constexpr VkDeviceSize Q2_LOGICAL_Q8=uint64_t(TOP)*OUT*8*256 + uint64_t(TOP)*16*256;
static constexpr uint32_t CHECKSUM_WORDS=59056;

struct PC { uint32_t mode,gate_type,down_type,in_dim,mid_dim,out_dim,n_tokens,n_selected,
    n_total_expert,gate_expert_bytes,gate_row_bytes,down_expert_bytes,down_row_bytes,
    q8_blocks; float clamp_value; uint32_t add_enabled,q2_words; };
struct Buf { VkBuffer b=VK_NULL_HANDLE; VkDeviceMemory m=VK_NULL_HANDLE; uint32_t type=0; };
static void ck(VkResult r,const char *s){if(r!=VK_SUCCESS){std::fprintf(stderr,"%s: %d\n",s,int(r));std::exit(2);}}
static uint32_t mt(VkPhysicalDevice p,uint32_t bits,VkMemoryPropertyFlags f){VkPhysicalDeviceMemoryProperties m;vkGetPhysicalDeviceMemoryProperties(p,&m);for(uint32_t i=0;i<m.memoryTypeCount;i++)if((bits&(1u<<i))&&(m.memoryTypes[i].propertyFlags&f)==f)return i;std::exit(2);}
static Buf buffer(VkPhysicalDevice p,VkDevice d,VkDeviceSize n,VkBufferUsageFlags u,VkMemoryPropertyFlags f){Buf x;VkMemoryPropertyFlags want=((u&(VK_BUFFER_USAGE_TRANSFER_SRC_BIT|VK_BUFFER_USAGE_TRANSFER_DST_BIT))==0)?VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT:f;VkBufferCreateInfo b{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};b.size=n;b.usage=u|((want&VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT)?VK_BUFFER_USAGE_TRANSFER_DST_BIT:0);ck(vkCreateBuffer(d,&b,nullptr,&x.b),"vkCreateBuffer");VkMemoryRequirements r;vkGetBufferMemoryRequirements(d,x.b,&r);VkMemoryAllocateInfo a{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};a.allocationSize=r.size;x.type=mt(p,r.memoryTypeBits,want);a.memoryTypeIndex=x.type;ck(vkAllocateMemory(d,&a,nullptr,&x.m),"vkAllocateMemory");ck(vkBindBufferMemory(d,x.b,x.m,0),"vkBindBufferMemory");return x;}
static std::vector<uint32_t> spv(const char *path){std::ifstream f(path,std::ios::binary|std::ios::ate);if(!f) {std::perror(path);std::exit(2);}auto n=f.tellg();f.seekg(0);std::vector<uint32_t>x((size_t(n)+3)/4);f.read((char*)x.data(),n);return x;}
static void put(VkDevice d,Buf x,const std::vector<uint8_t>&v){void*p;ck(vkMapMemory(d,x.m,0,v.size(),0,&p),"vkMapMemory");std::memcpy(p,v.data(),v.size());vkUnmapMemory(d,x.m);}
static void upload(VkPhysicalDevice p,VkDevice d,VkQueue q,VkCommandPool pool,VkCommandBuffer cmd,VkFence fence,Buf dst,const std::vector<uint8_t>&v){Buf s=buffer(p,d,v.size(),VK_BUFFER_USAGE_TRANSFER_SRC_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);put(d,s,v);vkResetFences(d,1,&fence);vkResetCommandBuffer(cmd,0);VkCommandBufferBeginInfo bi{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};ck(vkBeginCommandBuffer(cmd,&bi),"vkBeginCommandBuffer");VkBufferCopy c{0,0,v.size()};vkCmdCopyBuffer(cmd,s.b,dst.b,1,&c);ck(vkEndCommandBuffer(cmd),"vkEndCommandBuffer");VkSubmitInfo si{VK_STRUCTURE_TYPE_SUBMIT_INFO};si.commandBufferCount=1;si.pCommandBuffers=&cmd;ck(vkQueueSubmit(q,1,&si,fence),"vkQueueSubmit upload");ck(vkWaitForFences(d,1,&fence,VK_TRUE,UINT64_MAX),"vkWaitForFences upload");vkDestroyBuffer(d,s.b,nullptr);vkFreeMemory(d,s.m,nullptr);}
static uint64_t bytes_probe(const char *path){std::ifstream f(path);uint64_t x=0;std::string s;while(std::getline(f,s))if(s.find("[MHz]")!=std::string::npos){auto p=s.find('*');if(p!=std::string::npos)x=std::strtoull(s.substr(p+1).c_str(),nullptr,10);}return x;}
int main(int argc,char **argv){
  uint32_t iters=10; if(argc>1)iters=std::max(1u,(uint32_t)std::strtoul(argv[1],nullptr,10));
  VkApplicationInfo ai{VK_STRUCTURE_TYPE_APPLICATION_INFO};ai.apiVersion=VK_API_VERSION_1_2;VkInstanceCreateInfo ii{VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO};ii.pApplicationInfo=&ai;VkInstance ins;ck(vkCreateInstance(&ii,nullptr,&ins),"vkCreateInstance");
  uint32_t np=0;ck(vkEnumeratePhysicalDevices(ins,&np,nullptr),"vkEnumeratePhysicalDevices");std::vector<VkPhysicalDevice> ps(np);ck(vkEnumeratePhysicalDevices(ins,&np,ps.data()),"vkEnumeratePhysicalDevices");VkPhysicalDevice pd=ps[0];uint32_t nq=0;vkGetPhysicalDeviceQueueFamilyProperties(pd,&nq,nullptr);std::vector<VkQueueFamilyProperties> qp(nq);vkGetPhysicalDeviceQueueFamilyProperties(pd,&nq,qp.data());uint32_t qf=0;while(!(qp[qf].queueFlags&VK_QUEUE_COMPUTE_BIT))qf++;
  float pr=1;VkDeviceQueueCreateInfo qi{VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO};qi.queueFamilyIndex=qf;qi.queueCount=1;qi.pQueuePriorities=&pr;VkDeviceCreateInfo di{VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO};di.queueCreateInfoCount=1;di.pQueueCreateInfos=&qi;VkDevice dev;ck(vkCreateDevice(pd,&di,nullptr,&dev),"vkCreateDevice");VkQueue q;vkGetDeviceQueue(dev,qf,0,&q);
  VkCommandPoolCreateInfo ci{VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO};ci.queueFamilyIndex=qf;ci.flags=VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;VkCommandPool pool;ck(vkCreateCommandPool(dev,&ci,nullptr,&pool),"vkCreateCommandPool");VkCommandBufferAllocateInfo ca{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};ca.commandPool=pool;ca.level=VK_COMMAND_BUFFER_LEVEL_PRIMARY;ca.commandBufferCount=1;VkCommandBuffer cmd;ck(vkAllocateCommandBuffers(dev,&ca,&cmd),"vkAllocateCommandBuffers");VkFenceCreateInfo fi{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};VkFence fence;ck(vkCreateFence(dev,&fi,nullptr,&fence),"vkCreateFence");
  /* Top-6 buffers preserve the production expert-major,row-major addresses.
   * The benchmark shader consumes bytes; no model/output tensor is created. */
  std::vector<uint8_t> q8(Q8_IN), gate(2*GATE_TOP), down(DOWN_TOP), q80(Q80_BYTES), q80x(Q80_X_BYTES), ids(TOP*4), lut(544*4), checksum(CHECKSUM_WORDS*4);
  for(size_t i=0;i<q8.size();i++)q8[i]=uint8_t(i*13+7);for(size_t i=0;i<gate.size();i++)gate[i]=uint8_t(i*17+3);for(size_t i=0;i<down.size();i++)down[i]=uint8_t(i*19+5);for(size_t i=0;i<q80.size();i++)q80[i]=uint8_t(i*31+9);for(size_t i=0;i<q80x.size();i++)q80x[i]=uint8_t(i*37+13);for(uint32_t i=0;i<TOP;i++)std::memcpy(ids.data()+4*i,&i,4);for(size_t i=0;i<lut.size();i++)lut[i]=uint8_t(i*23+1);
  Buf b0=buffer(pd,dev,q8.size(),VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);Buf b1=buffer(pd,dev,gate.size(),VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);Buf b2=buffer(pd,dev,down.size(),VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);Buf b3=buffer(pd,dev,ids.size(),VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);Buf b4=buffer(pd,dev,checksum.size(),VK_BUFFER_USAGE_STORAGE_BUFFER_BIT|VK_BUFFER_USAGE_TRANSFER_DST_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);Buf b5=buffer(pd,dev,lut.size(),VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);Buf b6=buffer(pd,dev,q80.size(),VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);Buf b7=buffer(pd,dev,q80x.size(),VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);upload(pd,dev,q,pool,cmd,fence,b0,q8);upload(pd,dev,q,pool,cmd,fence,b1,gate);upload(pd,dev,q,pool,cmd,fence,b2,down);upload(pd,dev,q,pool,cmd,fence,b3,ids);upload(pd,dev,q,pool,cmd,fence,b5,lut);upload(pd,dev,q,pool,cmd,fence,b6,q80);upload(pd,dev,q,pool,cmd,fence,b7,q80x);put(dev,b4,checksum);
  auto code=spv("vulkan/shaders/spv/roofline_b_layout_decode.spv");VkShaderModuleCreateInfo smi{VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO};smi.codeSize=code.size()*4;smi.pCode=code.data();VkShaderModule sm;ck(vkCreateShaderModule(dev,&smi,nullptr,&sm),"vkCreateShaderModule");
  VkDescriptorSetLayoutBinding lb[8]{};for(uint32_t i=0;i<8;i++){lb[i].binding=i;lb[i].descriptorType=VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;lb[i].descriptorCount=1;lb[i].stageFlags=VK_SHADER_STAGE_COMPUTE_BIT;}VkDescriptorSetLayoutCreateInfo lci{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};lci.bindingCount=8;lci.pBindings=lb;VkDescriptorSetLayout sl;ck(vkCreateDescriptorSetLayout(dev,&lci,nullptr,&sl),"vkCreateDescriptorSetLayout");VkPushConstantRange pc{VK_SHADER_STAGE_COMPUTE_BIT,0,sizeof(PC)};VkPipelineLayoutCreateInfo pl{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};pl.setLayoutCount=1;pl.pSetLayouts=&sl;pl.pushConstantRangeCount=1;pl.pPushConstantRanges=&pc;VkPipelineLayout layout;ck(vkCreatePipelineLayout(dev,&pl,nullptr,&layout),"vkCreatePipelineLayout");VkComputePipelineCreateInfo cp{VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO};cp.stage={VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO};cp.stage.stage=VK_SHADER_STAGE_COMPUTE_BIT;cp.stage.module=sm;cp.stage.pName="main";cp.layout=layout;VkPipeline pipe;ck(vkCreateComputePipelines(dev,VK_NULL_HANDLE,1,&cp,nullptr,&pipe),"vkCreateComputePipelines");
  VkDescriptorPoolSize ds{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,8};VkDescriptorPoolCreateInfo dpi{VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};dpi.maxSets=1;dpi.poolSizeCount=1;dpi.pPoolSizes=&ds;VkDescriptorPool dp;ck(vkCreateDescriptorPool(dev,&dpi,nullptr,&dp),"vkCreateDescriptorPool");VkDescriptorSetAllocateInfo dai{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};dai.descriptorPool=dp;dai.descriptorSetCount=1;dai.pSetLayouts=&sl;VkDescriptorSet set;ck(vkAllocateDescriptorSets(dev,&dai,&set),"vkAllocateDescriptorSets");Buf bb[]={b0,b1,b2,b3,b4,b5,b6,b7};std::vector<VkDescriptorBufferInfo> bi(8);std::vector<VkWriteDescriptorSet>w(8);for(uint32_t i=0;i<8;i++){bi[i]={bb[i].b,0,VK_WHOLE_SIZE};w[i]={VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,nullptr,set,i,0,1,VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,nullptr,&bi[i],nullptr};}vkUpdateDescriptorSets(dev,8,w.data(),0,nullptr);
  VkQueryPoolCreateInfo qci{VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO};qci.queryType=VK_QUERY_TYPE_TIMESTAMP;qci.queryCount=2;VkQueryPool query;ck(vkCreateQueryPool(dev,&qci,nullptr,&query),"vkCreateQueryPool");PC p{0,16,10,IN,MID,OUT,1,TOP,TOTAL,uint32_t(GATE_BYTES),IQ2_ROW,uint32_t(DOWN_BYTES),Q2_ROW,16,0,0,1};
  VkCommandBufferBeginInfo cbi{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};VkSubmitInfo si{VK_STRUCTURE_TYPE_SUBMIT_INFO};si.commandBufferCount=1;si.pCommandBuffers=&cmd;
  VkPhysicalDeviceMemoryProperties memprops;vkGetPhysicalDeviceMemoryProperties(pd,&memprops);std::printf("shape=DS4_SHAPE_FLASH in=%u mid=%u out=%u experts=%u top6=%u\n",IN,MID,OUT,TOTAL,TOP);std::printf("memory_type_flags weight_iq2=%u weight_q2=%u weight_q8_0=%u activation_q8_0=%u properties_iq2=0x%x properties_q2=0x%x properties_q8_0=0x%x properties_activation=0x%x\n",b1.type,b2.type,b6.type,b7.type,memprops.memoryTypes[b1.type].propertyFlags,memprops.memoryTypes[b2.type].propertyFlags,memprops.memoryTypes[b6.type].propertyFlags,memprops.memoryTypes[b7.type].propertyFlags);std::printf("distinct_selected_bytes q8_k_input=%llu q8_0_activation=%llu q8_0_weight=%llu gate_iq2=%llu up_iq2=%llu down_q2=%llu weights_total=%llu output_tensor=0\n",(unsigned long long)Q8_IN,(unsigned long long)Q80_X_BYTES,(unsigned long long)Q80_BYTES,(unsigned long long)GATE_TOP,(unsigned long long)GATE_TOP,(unsigned long long)DOWN_TOP,(unsigned long long)(Q80_BYTES+2*GATE_TOP+DOWN_TOP));std::printf("logical_shader_read_bytes q8_0_weights=%llu q8_0_q8=%llu iq2_weights=%llu iq2_q8=%llu q2_weights=%llu q2_q8=%llu\n",(unsigned long long)Q80_BYTES,(unsigned long long)Q80_LOGICAL_Q8,(unsigned long long)(2*GATE_TOP),(unsigned long long)IQ2_LOGICAL_Q8,(unsigned long long)DOWN_TOP,(unsigned long long)Q2_LOGICAL_Q8);std::printf("dispatches_per_sample q8_0=1 iq2_gate_up=1 q2_down=1\n");std::printf("warm_upload_proof=weight_uploads_before_timing=1 weight_uploads_during_timing=0\n");
  auto run_family=[&](uint32_t mode,uint32_t gx,uint32_t gz){vkResetFences(dev,1,&fence);vkResetCommandBuffer(cmd,0);ck(vkBeginCommandBuffer(cmd,&cbi),"vkBeginCommandBuffer");vkCmdResetQueryPool(cmd,query,0,2);vkCmdBindPipeline(cmd,VK_PIPELINE_BIND_POINT_COMPUTE,pipe);vkCmdBindDescriptorSets(cmd,VK_PIPELINE_BIND_POINT_COMPUTE,layout,0,1,&set,0,nullptr);p.mode=mode;vkCmdPushConstants(cmd,layout,VK_SHADER_STAGE_COMPUTE_BIT,0,sizeof(p),&p);vkCmdWriteTimestamp(cmd,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,query,0);vkCmdDispatch(cmd,gx,1,gz);vkCmdWriteTimestamp(cmd,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,query,1);ck(vkEndCommandBuffer(cmd),"vkEndCommandBuffer");ck(vkQueueSubmit(q,1,&si,fence),"vkQueueSubmit");ck(vkWaitForFences(dev,1,&fence,VK_TRUE,UINT64_MAX),"vkWaitForFences");uint64_t ts[2];ck(vkGetQueryPoolResults(dev,query,0,2,sizeof(ts),ts,sizeof(uint64_t),VK_QUERY_RESULT_64_BIT|VK_QUERY_RESULT_WAIT_BIT),"vkGetQueryPoolResults");return ts[1]-ts[0];};
  uint64_t q8ticks=0,iq2ticks=0,q2ticks=0;for(uint32_t i=0;i<iters;i++){put(dev,b4,checksum);q8ticks+=run_family(0,32768,1);iq2ticks+=run_family(1,8,TOP);q2ticks+=run_family(2,820,1);}VkPhysicalDeviceProperties prop;vkGetPhysicalDeviceProperties(pd,&prop);std::vector<uint32_t> words(CHECKSUM_WORDS);void*mp;vkMapMemory(dev,b4.m,0,checksum.size(),0,&mp);std::memcpy(words.data(),mp,checksum.size());vkUnmapMemory(dev,b4.m);uint32_t sums[3]{};for(uint32_t i=0;i<32768;i++)sums[0]+=words[i];for(uint32_t i=32768;i<32816;i++)sums[1]+=words[i];for(uint32_t i=32816;i<CHECKSUM_WORDS;i++)sums[2]+=words[i];double q8ns=double(q8ticks)*prop.limits.timestampPeriod/iters,iq2ns=double(iq2ticks)*prop.limits.timestampPeriod/iters,q2ns=double(q2ticks)*prop.limits.timestampPeriod/iters;std::printf("gpu_ns q8_0=%.3f iq2_gate_up=%.3f q2_down=%.3f aggregate=%.3f checksum q8_0=%u iq2=%u q2=%u clocks_mhz=%llu temp=unknown iters=%u\n",q8ns,iq2ns,q2ns,q8ns+iq2ns+q2ns,sums[0],sums[1],sums[2],(unsigned long long)bytes_probe("/sys/class/drm/card0/device/pp_dpm_sclk"),iters);
  vkDeviceWaitIdle(dev);return 0;
}
